# Generated by Django 4.0.6 on 2022-07-06 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_toys_toy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeding',
            options={},
        ),
    ]
